Sort and Search functionality added to Table component
pancakeswap/pancake-uikit pull request #143
Opened 2021-01-20 00:06 UTC by cbunnydev

Table component is updated to be sorted by column
Table component is updated to be filtered by query

2021-01-20 03:10 UTC, hachiojidev requested changes
Is this supposed to be a draft? There are many linting errors that need to be fixed.

2021-01-20 06:56 UTC, cbunnydev commented
> 
> 
> Is this supposed to be a draft? There are many linting errors that need to be fixed.

No, this was fully functional, just needed to fix the linting errors.

2021-01-21 01:10 UTC, hachiojidev requested changes
Please keep this in a draft PR until the linting and prettier has been fixed. I recommend having Prettier format your file on each save.

2021-01-21 01:10 UTC, hachiojidev commented on src/components/Table/hooks.tsx
> +      prevPage: () => {},
Use Lodash's `noop`

2021-01-21 01:10 UTC, hachiojidev commented on src/components/Table/hooks.tsx
> +  render: HeaderRenderType | undefined
This should be `render?: HeaderRenderType`

2021-01-21 01:19 UTC, RabbitDoge commented
There is a lot of formatting problems. It looks like your prettier doesn't use the project config. Run `yarn format` to see the difference.

2021-01-25 01:31 UTC, hachiojidev approved these changes

2021-01-25 03:07 UTC, merged