style: Add small property to Toggle component
pancakeswap/pancake-uikit pull request #179
Opened 2021-02-09 20:04 UTC by heyimbrucelee

changed checked color from 'success' to 'secondary'

2021-02-10 06:43 UTC, RabbitDoge reviewed
I checked the result. Everything looks good.
Please add a test here https://github.com/pancakeswap/pancake-uikit/blob/master/src/__tests__/components/toggle.test.tsx for the `small` variant , and we can merge

2021-02-10 06:46 UTC, hachiojidev requested changes
Looks good. One thing - please use the same sizing pattern we use for other components. Check the `<Checkbox />` component for an example.

2021-02-10 06:47 UTC, RabbitDoge requested changes
The color changed has never been requested by our designer, please revert this change

2021-02-10 06:48 UTC, RabbitDoge commented
![image](https://user-images.githubusercontent.com/72658581/107475353-512ca680-6bb7-11eb-853e-7dac60855c36.png)

For your reference.
Please contact Chef Bugs if you need more details about the design

2021-02-12 05:51 UTC, RabbitDoge requested changes
The code is ok, but the pr still doesn't follow our coding rules.
If you don't know / want to use prettier, run `yarn format` before you commit.

2021-02-12 08:39 UTC, hachiojidev commented on src/components/Toggle/types.ts
> +}
Why do these extend `HTMLInputElement`?

2021-02-12 08:44 UTC, heyimbrucelee commented on src/components/Toggle/types.ts
> +}
bad ts knowledge :( , i'll fix it

2021-02-12 10:14 UTC, heyimbrucelee commented on src/components/Toggle/types.ts
> +}
i hope this time its ok !

2021-02-15 03:01 UTC, hachiojidev approved these changes

2021-02-15 03:16 UTC, RabbitDoge approved these changes

2021-02-15 03:17 UTC, merged