Bounty: easter-egg
pancakeswap/pancake-uikit pull request #192
Opened 2021-02-24 01:14 UTC by z3s

This PR adds useKonamiCheatCode hook and FallingBunnies component. that will be used in front-end.

2021-02-24 02:55 UTC, RabbitDoge requested changes
GJ. Some minor changes.
Please add a snapshot test for the bunny component.

2021-02-24 02:55 UTC, RabbitDoge commented on src/components/Svg/Icons/Bunny.tsx
> +import React from "react";
This icon probably exist here https://pancakeswap.github.io/pancake-uikit/?path=/story/components-svg-icons--icons

2021-02-24 02:55 UTC, RabbitDoge commented on src/components/FallingBunnies/FallingBunnies.tsx
> +const Bunny = styled.div<BunnyProps>`
Maybe add a `translate3d(0,0,0)` on the `transform` to enable GPU acceleration.

2021-02-24 02:55 UTC, RabbitDoge commented on src/components/FallingBunnies/FallingBunnies.tsx
> +  const bunnies = new Array(count).fill(undefined).map((_, index) => (
Prefer an ES6 syntax `[...Array(count)]`

2021-02-24 02:55 UTC, RabbitDoge commented on src/hooks/useKonamiCheatCode.ts
> +    function onKeyUpHandler(event: KeyboardEvent): void {
please use an arrow function.
return void is implicit I think.

2021-02-25 01:30 UTC, hachiojidev requested changes
Nice work.

2021-02-25 01:30 UTC, hachiojidev commented on src/components/FallingBunnies/FallingBunnies.tsx
> +    <Bunny key={String(index)} randPos={Math.random() * 100} iterations={iterations} duration={duration}>
Can you rename this to `position`.

2021-02-25 01:30 UTC, hachiojidev commented on src/components/FallingBunnies/types.ts
> +  key: string;
This is unecessary.

2021-02-25 01:30 UTC, hachiojidev commented on src/index.ts
> +export * from "./components/FallingBunnies";
Please put this in alphabetical order.

2021-02-25 01:30 UTC, hachiojidev commented on src/hooks/useKonamiCheatCode.stories.tsx
> +  useKonamiCheatCode(correctCodeHandler);
Instead of requiring the consumer to memoize the handler lets put it inside the hook itself using `useRef`.

2021-02-25 01:34 UTC, hachiojidev commented
@z3s One more thing I noticed. We can't accept this PR until the commits are fixed. They do not follow our linting rules.
https://docs.pancakeswap.finance/code/contributing#committing

2021-02-25 01:36 UTC, RabbitDoge commented
> @z3s One more thing I noticed. We can't accept this PR until the commits are fixed. They do not follow our linting rules.
> https://docs.pancakeswap.finance/code/contributing#committing

We can probably rewrite when we squash

2021-02-26 00:13 UTC, hachiojidev approved these changes

2021-02-26 06:08 UTC, RabbitDoge approved these changes

2021-02-26 06:09 UTC, merged